apiVersion: v1
kind: ConfigMap
metadata:
  name: survey-backend-config
  namespace: student-survey
data:
  ENVIRONMENT: production
  SQL_ECHO: "false"
  DB_POOL_SIZE: "5"
  DB_POOL_MAX_OVERFLOW: "10"
  DB_POOL_RECYCLE: "1800"
  # Allow the frontend origin by IP (no TLS yet)
  CORS_ORIGINS: '["http://100.26.217.148:30081"]'
