apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
  namespace: student-survey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-frontend
  template:
    metadata:
      labels:
        app: survey-frontend
    spec:
      containers:
        - name: survey-frontend
          image: kiran1703/survey-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-runtime-config
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: frontend-runtime-config
          configMap:
            name: survey-frontend-config
            items:
              - key: runtime-config.js
                path: runtime-config.js
---
apiVersion: v1
kind: Service
metadata:
  name: survey-frontend
  namespace: student-survey
spec:
  type: ClusterIP
  selector:
    app: survey-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
