apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-frontend
  namespace: student-survey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: survey-frontend
  template:
    metadata:
      labels:
        app: survey-frontend
    spec:
      containers:
        - name: survey-frontend
          image: kiran1703/survey-frontend:${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-runtime-config
              mountPath: /usr/share/nginx/html/runtime-config.js
              subPath: runtime-config.js
      volumes:
        - name: frontend-runtime-config
          configMap:
            name: survey-frontend-config
            items:
              - key: runtime-config.js
                path: runtime-config.js
---
apiVersion: v1
kind: Service
metadata:
  name: survey-frontend
  namespace: student-survey
spec:
  type: NodePort
  selector:
    app: survey-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
