apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: survey-ingress
  namespace: student-survey
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: survey.example.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: survey-backend
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: survey-frontend
                port:
                  number: 80
